# fly.toml app configuration file generated for nicks-brewin on 2023-12-16T22:13:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nicks-brewin"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  FLASK_ENV = "production"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
